#数据库配置
spring:
  datasource:
    url: jdbc:mysql://47.107.126.98:3306/person_manage?serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  thymeleaf:
    cache: false  #禁用thymeleaf的缓存
    prefix: classpath:/templates/ #配置thymeleaf的前缀

#配置mybatis-plus的映射文件
mybatis-plus:
  mapper-locations: classpath:/mybatis/mapper/*.xml    #映射文件
  config-location: classpath:/mybatis/mybatis-config.xml   #配置文件

#显示sql语句
logging:
  level:
    cn.zdxh.personnelmanage.mapper: debug

#图片上传的路径(自定义读取)
pic:
  visitPath: http://localhost:8080/pic/
            # http://47.107.126.98:8080/pic/
  savePath: E:/upload/picture/
            # /usr/java/upload/picture/

#项目访问路径前缀
#server:
#  servlet:
#    context-path: /pm





